### ISSUE TITLE
Gateblu on RaspberryPi keeps shutting down

### ISSUE THREAD

**Issue by brianehlert** [octoblu/issues#237]
It appears that it is getting a message telling it to shut down.

[gateblu.txt](https://github.com/octoblu/issues/files/39455/gateblu.txt)

**Comment by brianehlert** [comment]
Tried again yesterday, booted it and it came up then shutdown.

[gateblu.txt](https://github.com/octoblu/issues/files/51185/gateblu.txt)

**Comment by brianehlert** [comment]
Performed a global NPM update and the shutdown issue stopped.
sudo npm update -g
this updated:
node-gyp@3.2.0 
node-pre-gyp@0.6.17 
npm@3.5.1

**Comment by brianehlert** [comment]
This has started happening again.
Gateblu 5.0.5 - just the service (gateblu-forever)

**Comment by peterdemartini** [comment]
@brianehlert can you send us the most recent logs?

**Comment by brianehlert** [comment]
Sorry for the delay.
The log ends with: "Gateblu shutdown"

[gateblu.txt](https://github.com/octoblu/issues/files/105233/gateblu.txt)

**Comment by iamruinous** [comment]
It looks like there is a timeout happening that is then triggering the uncaughtException handling. I added some logging and hopefully captured that particular exception. Try v5.0.9 and see if that works better.

**Comment by brianehlert** [comment]
[gateblu.txt](https://github.com/octoblu/issues/files/107562/gateblu.txt)

24+ hours later..  Not responding again.

**Comment by peterdemartini** [comment]
@brianehlert I fixed that error in v6.0.5, can you try it again?

**Comment by brianehlert** [comment]
@peterdemartini  I am guessing that the NPM was not updated?  Since npm update for gateblu-forever is not doing anything this go about.
(it worked just peachy with Jade's last change to update to 5.0.9)

**Comment by brianehlert** [comment]
Seems that update doesn't work, (I must be remembering incorrectly) but running install again does pull the latest.

**Comment by peterdemartini** [comment]
@brianehlert can you explain more about the problem with the 6.0.5 version?.

**Comment by brianehlert** [comment]
It was just me expecting npm update to work.
Once I did npm install the new version was pulled.
version 6.0.5 has now been running for two days.  Looks promising.
I will keep it running over the weekend before closing this.

**Comment by brianehlert** [comment]
Still working.  Closing.

**Comment by brianehlert** [comment]
Did it again over the weekend.
It shut down.  Cleanly noted in the log.
[gateblu.txt](https://github.com/octoblu/issues/files/122011/gateblu.txt)

**Comment by sqrtofsaturn** [comment]
@brianehlert I think I fixed that specific error, can you try version 6.0.7?

**Comment by brianehlert** [comment]
This is still happening.
This time Gateblu 6.3.1
[gateblu.txt](https://github.com/octoblu/issues/files/148550/gateblu.txt)

**Comment by brianehlert** [comment]
This persists.
Is it possible to move this issue over to Gateblu-forever?  Since this happens on Linux as well, when using Gateblu-forever.
[gateblu.txt](https://github.com/octoblu/issues/files/174987/gateblu.txt)

**Comment by peterdemartini** [comment]
@brianehlert I am deploying v6.4.3 with a fix for the meshblu reconnects.

Next time you run into this issue, create the issue in gateblu-forever. I don't think there is a way to transfer it.
